name: CMake Build Matrix

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download PCL (Windows)
      shell: pwsh
      run: |
        $pcldir="$((Get-Item ..).FullName)\pcl"
        mkdir $pcldir
        (New-Object System.Net.WebClient).DownloadFile("https://github.com/PointCloudLibrary/pcl/releases/download/pcl-1.12.1/PCL-1.12.1-AllInOne-msvc2019-win64.exe","$pcldir\pcl-installer.exe");
    - name: Install PCL (Windows)
      shell: pwsh
      run: |
        $pcldir="$((Get-Item ..).FullName)\pcl"
        $pclinst="$pcldir\pcl-installer.exe"
        $proc = New-Object System.Diagnostics.Process -Property @{
            StartInfo = New-Object System.Diagnostics.ProcessStartInfo("$pclinst", "/S")
        }

        $proc.Start()
        $proc.WaitForExit()
        dir
    - name: See what is there
      if: always()
      shell: bash
      run: |
        du ..
        ls -l "/c/Program Files"

    - name: build
      uses: ashutoshvarma/action-cmake-build@master
      with:
        build-dir: ${{ github.workspace }}/build
        build-type: Release
        run-test: true

